---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars:
    pkgs:
      - htop
      - iotop
      - git
      - chrony
      - sysstat
      - vim
      - tmux
      - tree
      - tcpdump
      - unzip
      - libpcre3-dev
      - libssl-dev
      - perl
      - make
      - cmake
      - automake
      - m4
      - peg
      - libtool
      - autoconf
      - zlib1g-dev
      - build-essential
      - curl
      - python3-pip
      - debian-archive-keyring
      - apt-transport-https
      - golang-go

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Update Apt Cache
      apt:
        update_cache: yes
        cache_valid_time: 86400
        force_apt_get: yes

    - name: Ubuntu Packages
      apt: >
        pkg={{ pkgs }}
        state=present


  post_tasks:
    - name: Get the Agent
      get_url:
        url: https://download.newrelic.com/install/newrelic-cli/scripts/install.sh
        dest: "/var/tmp/newrelic-installer.sh"
        validate_certs: no
    - name: Install the agent
      command: /bin/bash /var/tmp/newrelic-installer.sh
      args:
        creates: /usr/local/bin/newrelic
#    - name: Install the agent
#      command: /usr/local/bin/newrelic install
#      args:
#        creates: /usr/local/bin/newrelic-plugin-agent
#      environment:
#        NEW_RELIC_API_KEY: "{{ new_relic_api_key }}"
#        NEW_RELIC_ACCOUNT_ID: "{{ new_relic_account_id }}"
